### ISSUE TITLE
Need to change bodyText2 to body2

### ISSUE THREAD

**Issue by nhwilly** [ResoCoder/finished-flutter-firebase-ddd-course#4]
Just a typo, but downloading the package yielded a number of errors.

There are references to: 
`style: Theme.of(context).primaryTextTheme.bodyText2` 

when they should be: 
`style: Theme.of(context).primaryTextTheme.body2`

That cleaned it up.  I'd put in a pull request, but I don't know how.

**Comment by ResoDev** [comment]
Thanks for filing the issue! I guess I like to live dangerously because I built this project on a dev version of Flutter which has undergone some updates to theme naming. I'll leave it unchanged since a stable version of Flutter with these changes is just around the corner.
