### ISSUE TITLE
TextFormField not validating correctly

### ISSUE THREAD

**Issue by VGJohn** [ResoCoder/finished-flutter-firebase-ddd-course#6]
The 'validated value objects' EmailAddress and Password aren't triggering the TextFormField validation on the Sign In form correctly. The value objects are always one character input behind the actual input in the TextFormField because the validator doesn't run when the widgets are rebuilt, only when the TextFormField input changes so its always using the previous bloc state. 

I think you should be retrieving the current bloc state within the validator to avoid this but maybe there is a better solution?

**Comment by VGJohn** [comment]
![validationbug](https://user-images.githubusercontent.com/22520267/79453954-51cdce00-7fe2-11ea-8ca6-78cc2ed8b181.gif)

**Comment by VGJohn** [comment]
Attach a gif of the issue just to make things a bit clearer, as you can see the password validation is checking for at least 6 characters but the validation logic is saying that 6 character isn't valid sometimes and 5 characters is valid other times. Same issue occurs with the email validation.

**Comment by ResoDev** [comment]
Getting the "fresh" Bloc state is most likely the only solution. That's because the `validator` function always runs before the `BlocConsumer` had a chance to rebuild the UI and supply the updated state to the `builder` function
