### ISSUE TITLE
bodyText2 attribute not found in TextTheme Class

### ISSUE THREAD

**Issue by prajwal27** [ResoCoder/finished-flutter-firebase-ddd-course#9]
Error found in note_form_page.dart and error_note_card_widget.dart.

![Screenshot from 2020-04-29 05-43-19](https://user-images.githubusercontent.com/31249460/80550072-7bbcc280-89dc-11ea-9f46-85d5d34964dd.png)

A possible fix is to change **bodyText2**  to **body2**.

**Comment by ResoDev** [comment]
Hello, this project was built on the beta/dev versions of Flutter. A new stable version should come out soon and this "error" will be gone, as there are some name changes in the new version.
